language: scala
scala:
- 2.10.5
- 2.11.6
script:
- sbt coverage test coverageReport coveralls
after_success:
- '[[ $TRAVIS_BRANCH == "master" ]] && { sbt publish; };'
env:
  global:
  - secure: HVx5Vh01z1KtTTLExTkougxpIbNdvgcLen1B4Tv5XoyQKzgqzQTjvWANwrR0t9TwC2PFbo/2f7CzMy4FKXE5IeswXQgtIR1s3VHzw8iLPUF9vXcgsPGM8kThaMxkpuJCk9bxTnxYn3UFKM4ptFjZ9mInfg1KjXvjT+230yROxos=
  - secure: K61QCYH74fqRpLAjGYxF+0910gq4oB9bW2+UOku5OVBzqEPLTizsnlvdqyscR+9ErhJTqGyvuqGKi7APlAOQkVDgRT5TEWa0IaD3U8BaGFDhvG3q9lunpuy8ybQ/MYw+1ZVu+RUajF1QZ2Y1EwpTGRnX2+/AlaFv/ixE7+6KOoU=
  - secure: J2y9sNFjVobIAHm/w3DxQ0s05yvttLK2VSgpkkZcEV5n7z+L+LimI+aG8EUS8Si7jsM0ZGrtkx7/dM0MRDnrcFUGUk+bCTzT2lc0VXxt60L4L2vMBs3ysteBF1ihXCh+GAmgqUjVPCNEH80aHciYjMcEq2kphkoR72hUnlr8/xE=
